Lab1 - Jerusalimov
Mikhail-M12/PiAA_9382_LETI2021 pull request #10
Opened 2021-03-17 00:33 UTC by NereusOcean

2021-03-17 09:36 UTC, thehighestmath requested changes

2021-03-17 09:36 UTC, thehighestmath commented on lab1/src/main.cpp
> +#define space std::string("\n____________________________________________\n");
Макросы -- это зло, лучше юзать `const/constexpr` https://docs.microsoft.com/ru-ru/cpp/cpp/constexpr-cpp?view=msvc-160

2021-03-17 09:36 UTC, thehighestmath commented on lab1/src/main.cpp
> +    int **map;
Лучше бы конечно STL контейнер знать, например `std::array<int>` Memory leak(
![image](https://user-images.githubusercontent.com/42893255/111445085-1967d000-871c-11eb-9783-7e9a038eb2f8.png)

2021-03-17 09:36 UTC, thehighestmath commented on lab1/src/main.cpp
> +}
Может лучше попробовать сделать шаблонную функцию, чтобы не было дублирования кода (*)

2021-03-17 09:36 UTC, thehighestmath commented on lab1/src/main.cpp
> +                }
(*) Например вот, если * была бы шаблоном, то это можно было бы в неё закинуть ;)

2021-03-17 09:44 UTC, thehighestmath commented
Кажется форматирование поехало(
![image](https://user-images.githubusercontent.com/42893255/111446729-c3942780-871d-11eb-9d69-55ca5fa02f2f.png)
Кровь из глаз(((
![image](https://user-images.githubusercontent.com/42893255/111446932-fb9b6a80-871d-11eb-8c95-0aada96f83eb.png)


Тема вроде как _Поиск с возвратом_
![image](https://user-images.githubusercontent.com/42893255/111446889-ecb4b800-871d-11eb-8e48-863fc189b4fc.png)


Вроде как Big O оценивают сложности, little o юзают для других целей
![image](https://user-images.githubusercontent.com/42893255/111447059-1cfc5680-871e-11eb-89bf-e90d5dd7daab.png)


Кажется опять too much отступ для слова _Выводы_
![image](https://user-images.githubusercontent.com/42893255/111447317-62208880-871e-11eb-9e28-459aab2c4c79.png)

2021-03-17 12:55 UTC, thehighestmath commented
1. Форматирование задания до сих пор не норм
![image](https://user-images.githubusercontent.com/42893255/111470482-f697e480-8738-11eb-94d7-3d9b126ddf3a.png)

Отступы не равны, а заголовки должны иметь одинаковый отступ
![image](https://user-images.githubusercontent.com/42893255/111470512-fe578900-8738-11eb-98d0-8e50bce5c77e.png)

2. Код в отчете другой(

2021-03-17 14:33 UTC, thehighestmath commented
__Проверено__

1. (+) мало комментариев в коде, + местами кодировка битая(

Зачтено на 4 очка, +фя

Добор плюсика не снимет попытку

2021-03-17 14:36 UTC, thehighestmath commented on lab1/src/main.cpp
> +}
Ну такое, шаблона не увидел( На защите об этом поговорим)

2021-03-17 14:36 UTC, thehighestmath approved these changes

2021-03-17 15:02 UTC, thehighestmath commented
Когда защищаться будешь?)

2021-03-17 15:36 UTC, NereusOcean commented
Готов хоть сейчас

2021-03-23 13:19 UTC, thehighestmath commented
Пулл реквест закрою, но если захочешь добрать плюсиков -- исправь отчет и **переоткрой** пулл реквест, **не создавай новый**

2021-04-02 08:40 UTC, Mikhail-M12 commented
Нарушены правила работы с репозиторием. Очки аннулируются до исправлений.

2021-04-07 10:27 UTC, NereusOcean commented
Исправил

2021-04-07 22:09 UTC, thehighestmath commented
Правила соблюдены

2021-04-07 22:09 UTC, closed without merging