Mikhailov_lab1
Mikhail-M12/PiAA_9382_LETI2021 pull request #11
Opened 2021-03-21 17:17 UTC by BabylonExile

var 1i
Lab - Done
Report - In progress

2021-03-21 17:22 UTC, thehighestmath commented
Отчёта, мэйкфайла, тестов -- нет

2021-03-21 17:44 UTC, thehighestmath commented on Mikhailov/lab1/main.cpp
> +    void createOptimalDivision()
Я, конечно, не эксперт, но эта функция, которая отвечает за создание оптимального деления (сигнатура такая) точно ли должна печатать результат?

2021-03-21 17:48 UTC, thehighestmath requested changes

2021-03-21 17:48 UTC, thehighestmath commented on Mikhailov/lab1/main.cpp
> +    bool findEmpty(size_t &x, size_t &y) {
Ох, я уже кому-то писал, что это не оч изменять значения по ссылке... Точно ли без этого нельзя?

2021-03-21 17:48 UTC, thehighestmath commented on Mikhailov/lab1/main.cpp
> +                    std::cout << std::to_string(i * compression + 1) + " " +
А если не оборачивать в `std::to_string` всё сломается?

2021-03-23 06:25 UTC, Mikhail-M12 commented
Вариант 1и занят Герасевым, Вам придётся сделать другой вариант. Срок дедлайна 1 для Вас переносится на 15 апреля. Если принесёте справку от врача с печатью ЛЭТИ, то получите ещё сдвиг сроков.

2021-03-27 22:11 UTC, BabylonExile commented
переписал на новый вариант, отчет, скрипт, всё в норме

2021-03-27 22:17 UTC, thehighestmath requested changes
Проверить вариант.

2021-03-27 22:17 UTC, thehighestmath commented on Mikhailov/lab1/src/main.cpp
> +using namespace std;
Лучше не привыкать писать такую строчку, а то в будущем можно будет захотеть написать `using namespace other_namespace;` и тогда может начаться конфликт имён(

2021-03-27 22:17 UTC, thehighestmath commented on Mikhailov/lab1/src/main.cpp
> +    /* Процедуры квадрирования */
Процедуры?) А разве не методы?)

2021-03-27 22:17 UTC, thehighestmath commented on Mikhailov/lab1/src/main.cpp
> +    bool findEmpty(size_t &x, size_t &y) {
А зачем  `x, y` передавать по ссылке? Мы их ходим менять? А функция возвращает `bool` не очевидно, что входные параметры будут использоваться дальше, вернее не понятно для чего...(

2021-03-27 22:17 UTC, thehighestmath commented on Mikhailov/lab1/src/main.cpp
> +                    updateOptimalDivision(copyX, copyY, deep++);
Такс-такс-такс. Кажется у тебя итеративный вариант, а тут я вижу рекурсию. Как быть?

2021-03-27 22:18 UTC, thehighestmath commented
![image](https://user-images.githubusercontent.com/42893255/112736419-7dcc3000-8f63-11eb-9b22-14834ccf36aa.png)
Ещё и отчет не очень(

2021-03-28 00:42 UTC, BabylonExile commented
1. С номером варианта произошла путаница, взят вариант 4р, реализован рекурсивный бэктрекинг, который я использовал в первоначальном варианте своей программы.
2. От using namespace std избавился.
3. Параметры x, y больше не передаются по сслыке, теперь метод findEmpty возвращает структуру.
4. Отчет поправлен.

2021-03-28 11:11 UTC, thehighestmath commented
__Проверено__

1. Нет оценок по сложностям
2. (+) Не понятно как происходит снятие квадратов
![image](https://user-images.githubusercontent.com/42893255/112750148-69258180-8fcf-11eb-9c25-3fb515852d3a.png)
_Что происходит тут?_


Зачтено на 2,5 очка, +фк

2021-03-28 11:12 UTC, thehighestmath approved these changes

2021-03-28 22:37 UTC, BabylonExile commented
1. Оценка сложности алгоритма добавлена в отчет.
2. Промежуточный вывод исправлен, теперь координаты удаляемых квадратов корректные.

2021-03-29 07:06 UTC, thehighestmath commented
1. Сложность по времени -- согласен. О сложности по памяти поговорим на защите, если убедишь -- то балл верну
2. (+) Не понятно почему квадратики удаляются (наверное удаляются все единичные и первый не единичный, ну или как-то ещё. Этот момент не понятен, а не координаты квадратов(( ) 

А так

Зачтено, 3 очка, +фк

2021-03-29 09:13 UTC, thehighestmath commented
В целом можно защищаться, готов сегодня?)

2021-04-02 08:15 UTC, Mikhail-M12 commented
Нарушены правила работы с репозиторием. Очки аннулируются до исправления.

2021-04-02 18:44 UTC, BabylonExile commented
Исправлено наименование отчета

2021-04-04 22:30 UTC, thehighestmath commented
Правила работы с репозиторием выполнены

2021-04-04 22:30 UTC, closed without merging