Ryzhikh - lab1
Mikhail-M12/PiAA_9382_LETI2021 pull request #19
Opened 2021-03-25 09:47 UTC by Ryzhikh-Roman

Lab1 done

2021-03-25 09:56 UTC, thehighestmath commented
Не полный пакет для сдачи

2021-03-25 09:59 UTC, thehighestmath requested changes

2021-03-25 09:59 UTC, thehighestmath commented on Ryzhikh/lab1/src/main.cpp
> +using namespace std;
Убираем

2021-03-25 09:59 UTC, thehighestmath commented on Ryzhikh/lab1/src/main.cpp
> +vector<pair<int, pair<int, int>>> resArr;
Глобольные переменные -- зло

2021-03-25 09:59 UTC, thehighestmath commented on Ryzhikh/lab1/src/main.cpp
> +void insertBlock(vector<vector<bool>>& mainArr, int m, int x, int y) //������� �������� �������� m * m � ����� ������� ����� � ����� (x, y)
Кодировку лучше поправить

2021-03-25 09:59 UTC, thehighestmath commented on Ryzhikh/lab1/src/main.cpp
> +void removeBlock(vector<vector<bool>>& mainArr, int m, int x, int y) //������� �������� �������� m * m � ����� ������� ����� � ����� (x, y)
Кодировку лучше поправить (2)

2021-03-25 09:59 UTC, thehighestmath commented on Ryzhikh/lab1/src/main.cpp
> +pair<int, int> findEmpty(vector<vector<bool>>& mainArr) //����� ������ ��������� ������ ��� �������
Кодировку лучше поправить (3)

2021-03-25 09:59 UTC, thehighestmath commented on Ryzhikh/lab1/src/main.cpp
> +    if (maxSize.second)                                                        //���� ����� �������� ����� ���� ������������� �������
Кодировку лучше поправить (4)

2021-03-25 09:59 UTC, thehighestmath commented on Ryzhikh/lab1/src/main.cpp
> +        chooseBlock(mainArr, tmpArr, counter + 1, x, y); //��������� ��������� ����
Кодировку лучше поправить (5)

2021-03-25 09:59 UTC, thehighestmath commented on Ryzhikh/lab1/src/main.cpp
> +            chooseBlock(mainArr, tmpArr, counter + 1, x, y); //��������� ��������� ����
Кодировку лучше поправить (6)

2021-03-25 09:59 UTC, thehighestmath commented on Ryzhikh/lab1/src/main.cpp
> +void primeNumber(vector<vector<bool>>& mainArr) //������� ��������� ������ � ������ ������ �����������
Кодировку лучше поправить (7)

2021-03-25 09:59 UTC, thehighestmath commented on Ryzhikh/lab1/src/main.cpp
> +    //�������� "�����" ����������
Кодировку лучше поправить (8)

2021-03-25 10:01 UTC, thehighestmath commented
![image](https://user-images.githubusercontent.com/42893255/112454776-172ff200-8d6a-11eb-8dc5-4be251a935f2.png)
Кажется, что на степике были входные данные, а еще и форматирование чуть-чуть другое

2021-03-25 10:07 UTC, thehighestmath commented on Ryzhikh/lab1/src/main.cpp
> +    vector<vector<bool>> mainArr(N);
`vector<vector<bool>> mainArr(N);` 2D массив из bool'ов для демонстрации норм заходит?)

2021-03-25 10:07 UTC, thehighestmath requested changes

2021-03-25 10:07 UTC, thehighestmath commented on Ryzhikh/lab1/src/main.cpp
> +vector<pair<int, pair<int, int>>> resArr;
`vector<pair<int, pair<int, int>>> resArr;`

2021-03-25 10:11 UTC, thehighestmath requested changes

2021-03-25 10:11 UTC, thehighestmath commented on Ryzhikh/lab1/src/main.cpp
> +vector<pair<int, pair<int, int>>> resArr;
`vector<pair<int, pair<int, int>>> resArr;` я только сейчас понял что ты тут хотел выразить, но вектор из пар, в котором один из элементов пары -- пара, это сильно.
Давай для квадратов сделаем красивее структуру
Чтобы не городить такое потом
`resArr[i].second.first * scale + 1 << ' ' << resArr[i].second.second * scale + 1 << ' ' << resArr[i].first * scale`

2021-03-25 10:30 UTC, Ryzhikh-Roman commented on Ryzhikh/lab1/src/main.cpp
> +vector<pair<int, pair<int, int>>> resArr;
Без глобальных переменных можно, но некоторые функции будут забиты аргументами. В такой небольшой программе точно с ними нельзя?

2021-03-25 10:59 UTC, thehighestmath commented on Ryzhikh/lab1/src/main.cpp
> +vector<pair<int, pair<int, int>>> resArr;
Сделай класс

2021-03-25 11:21 UTC, thehighestmath requested changes

2021-03-25 11:21 UTC, thehighestmath commented on Ryzhikh/lab1/src/main.cpp
> +    std::vector<std::pair<int, std::pair<int, int>>> resArr;
Не исправил

2021-03-25 11:23 UTC, Ryzhikh-Roman commented on Ryzhikh/lab1/src/main.cpp
> +    std::vector<std::pair<int, std::pair<int, int>>> resArr;
Это относится к вектору пар?

2021-03-25 11:35 UTC, Ryzhikh-Roman commented on Ryzhikh/lab1/src/main.cpp
> +    std::vector<std::pair<int, std::pair<int, int>>> resArr;
Если да, то почему его нельзя использовать?
Структуры более понятнее, но программа уже построена на логике, связанной с парами. Координаты изначально были объединены в пары, затем, для связи с величиной квадрата, использовалась пара поверх пары. Выглядит неэстетично, но имеет место быть, разве нет?

2021-03-25 11:38 UTC, thehighestmath commented on Ryzhikh/lab1/src/main.cpp
> +    std::vector<std::pair<int, std::pair<int, int>>> resArr;
Вектор пар использовать можно, но не вектор пар пар

2021-03-25 11:41 UTC, Ryzhikh-Roman commented on Ryzhikh/lab1/src/main.cpp
> +    std::vector<std::pair<int, std::pair<int, int>>> resArr;
Почему нет?

2021-03-25 11:42 UTC, Ryzhikh-Roman commented on Ryzhikh/lab1/src/main.cpp
> +    std::vector<std::pair<int, std::pair<int, int>>> resArr;
Его, может, "не стоит" использовать, но почему его "нельзя" использовать?

2021-03-25 11:42 UTC, thehighestmath approved these changes

2021-03-25 11:52 UTC, thehighestmath commented
__Проверено__

1. Нет сложности по памяти
2. Нет никако отладочной информации
3. (+) Нет ясности выполнения программы 5 `std::cout` это явно не тот уровень вывода данных на экран :)
4. (+) Нет принимаемых аргументов
> Описание функций и структур данных

Зачтено на 2 очка, +к

2021-03-29 09:15 UTC, thehighestmath commented
_Переживаю_

2021-04-04 18:19 UTC, thehighestmath commented
Скучаю

2021-04-12 08:00 UTC, thehighestmath commented
Закрою пулл реквест, потом переоткрой, когда захочешь что-то исправить

2021-04-27 11:05 UTC, Ryzhikh-Roman commented
Не могу переоткрыть этот пулреквест
![image](https://user-images.githubusercontent.com/54955488/116231496-a19cb480-a761-11eb-9451-cb4cc213332c.png)

2021-04-27 11:13 UTC, thehighestmath commented
Переоткрыл

2021-04-27 11:13 UTC, Ryzhikh-Roman commented
Спасибо

2021-04-27 15:39 UTC, Ryzhikh-Roman commented
Работа готова к проверке.

2021-04-27 21:27 UTC, thehighestmath commented
Очет переименовать
![image](https://user-images.githubusercontent.com/42893255/116314316-9d02eb00-a7b7-11eb-98ae-eeae2a96ce10.png)

---------------

:( 
![image](https://user-images.githubusercontent.com/42893255/116314413-c28ff480-a7b7-11eb-915f-72070dadca11.png)

-----------------

__Проверено__

1. Нет сложности по памяти (ок)
2. Нет никакой отладочной информации (не ок)
3. (+) Нет ясности выполнения программы 5 std::cout это явно не тот уровень вывода данных на экран :) (не ок)
![image](https://user-images.githubusercontent.com/42893255/116314898-64174600-a7b8-11eb-8aa9-79d0e1776798.png)
_хочется видеть рисование столешницы после вставки новых квадратов и после их замены_
4. (+) Нет принимаемых аргументов (ок)

Зачтено на 3 очка, +фк

2021-04-27 23:30 UTC, Ryzhikh-Roman commented
По поводу вывода столешницы.
В программе есть довольно сильное упрощение всего алгоритма в виде делимости размера столешницы на 3 и 5. В таких случаях размер столешницы просто уменьшается до чисел 3 и 5 соответственно.  Можно ли тогда выводить столешницу не начальную, а уменьшенную?

2021-04-28 04:51 UTC, thehighestmath commented
Да

ср, 28 апр. 2021 г., 02:30 Ryzhikh-Roman ***@***.***>:

> По поводу вывода столешницы.
> В программе есть довольно сильное упрощение всего алгоритма в виде
> делимости размера столешницы на 3 и 5. В таких случаях размер столешницы
> просто уменьшается до чисел 3 и 5 соответственно. Можно ли тогда выводить
> столешницу не начальную, а уменьшенную?
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/Mikhail-M12/PiAA_9382_LETI2021/pull/19#issuecomment-828018454>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AKHH7RYR4JAP2RKK4GN6NKTTK5CJPANCNFSM4ZY767KA>
> .
>

2021-04-28 12:16 UTC, Mikhail-M12 commented
Пока отчёт не переименован, очки считаются неначисленными.

2021-04-28 12:22 UTC, thehighestmath commented
В дальнейшем так и буду поступать. А проверять работу можно в таком случае?
Или лучше не стоит?

ср, 28 апр. 2021 г., 15:16 Mikhail-M12 ***@***.***>:

> Пока отчёт не переименован, очки считаются неначисленными.
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/Mikhail-M12/PiAA_9382_LETI2021/pull/19#issuecomment-828406050>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AKHH7R45SLAZ54IFVNC75S3TK74BXANCNFSM4ZY767KA>
> .
>

2021-04-28 12:27 UTC, Mikhail-M12 commented
Согласно алгоритму дистанционной проверки, изложенному в Readme.md, проверять работу не надо до появления необходимых исправлений.

2021-04-28 12:31 UTC, thehighestmath commented
Справедливо. Спасибо за пояснения

ср, 28 апр. 2021 г., 15:27 Mikhail-M12 ***@***.***>:

> Согласно алгоритму дистанционной проверки, изложенному в Readme.md,
> проверять работу не надо до появления необходимых исправлений.
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/Mikhail-M12/PiAA_9382_LETI2021/pull/19#issuecomment-828413201>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AKHH7RZG2J7IEYO6CESGHALTK75M5ANCNFSM4ZY767KA>
> .
>

2021-04-28 14:25 UTC, Ryzhikh-Roman commented
Исправлено и готово к проверке.
Добавлен define с выводом столешницы. Для столешницы, размер которой чётный, ничего не выводится, а в отладочной информации пишется, что это тривиальный случай и что минимальное количество квадратов всегда 4 (по углам)

2021-04-28 18:17 UTC, thehighestmath commented
__Проверено__

__Зачтено__ на 4 очка, +фкя

2021-04-28 19:00 UTC, Ryzhikh-Roman commented
Когда можно защититься?

2021-04-28 19:20 UTC, thehighestmath commented
Если не спишь, то можно через минут 10 в дискорде встретиться

2021-04-28 19:59 UTC, closed without merging