Golubeva - lab3
Mikhail-M12/PiAA_9382_LETI2021 pull request #23
Opened 2021-03-29 19:48 UTC by Valentina-Gol

2021-03-30 08:31 UTC, thehighestmath commented
__Проверено__

1. Не согласен со сложностями по времени и памяти (да и тут какой-то little-o, а нужен big-O)
2. (+) можно чуть больше коментариев в коде?)
3. (+) не понятно как в промежуточных данных ищется путь

Зачтено на 2,5 очка, +ф

2021-03-30 08:44 UTC, thehighestmath requested changes

2021-03-30 08:47 UTC, thehighestmath commented on Golubeva/lab3/src/l3.py
> +        visited = self.row * [False] #list
Как будто так понятнее
![image](https://user-images.githubusercontent.com/42893255/112961001-a31c9200-914d-11eb-9cd8-d097e26170ae.png)
Вот прмиер со строками
```suggestion
        visited =  [False] * self.row #list
```

2021-03-30 08:47 UTC, thehighestmath commented on Golubeva/lab3/src/l3.py
> +        parent = self.row * [-1]
![image](https://user-images.githubusercontent.com/42893255/112961065-b0d21780-914d-11eb-9bc3-be5798f8adc5.png)
Такое же пожелание

2021-03-31 13:57 UTC, Valentina-Gol commented
Исправлено

2021-03-31 14:39 UTC, thehighestmath commented
Пау
![image](https://user-images.githubusercontent.com/42893255/113162193-bf9cf500-9247-11eb-8a4f-fcdb6c5cb5f7.png)

Пау
![image](https://user-images.githubusercontent.com/42893255/113162263-cd527a80-9247-11eb-8111-39a49acf1d60.png)

Пау
![image](https://user-images.githubusercontent.com/42893255/113162436-fb37bf00-9247-11eb-8862-37723bfecaf9.png)

2021-03-31 14:40 UTC, thehighestmath commented
И кажется задание в отчете форматирование потеряло(

2021-03-31 14:43 UTC, thehighestmath commented
Программа не завершается, приходится делать `segint`

2021-04-01 08:39 UTC, thehighestmath commented
Проверено

1. Исправлено
2. (+) Исправлено
3. (+) Не исправлено
Зачтено на 4 очка, +фк

2021-04-01 08:40 UTC, thehighestmath reviewed
На защите поговорим о коде :)

2021-04-01 11:00 UTC, closed without merging