lab3 - Pya
Mikhail-M12/PiAA_9382_LETI2021 pull request #29
Opened 2021-04-03 20:14 UTC by SonKhwa

2021-04-03 21:12 UTC, thehighestmath requested changes

2021-04-03 21:12 UTC, thehighestmath commented on Pya/lab3/src/main.cpp
> +}
Хм, а разве одна из другой не получается простым отрицанием? (да там будет иметь место равно, но настолько ли это важно, чтобы создавать ещё один метод?)

2021-04-03 21:12 UTC, thehighestmath commented on Pya/lab3/src/main.cpp
> +using Weight = int;
А это зачем?)

2021-04-03 21:12 UTC, thehighestmath commented on Pya/lab3/src/main.cpp
> +    }
А зачем нам в конструктор нужно передавать приопущенный поток? _разве он изначально не равен нулю? Если так, то кажется не очень много смыла передавать его в конструктор :)_

2021-04-03 21:12 UTC, thehighestmath commented on Pya/lab3/src/main.cpp
> +        for (auto &key: graph) graph[key.first].sort(lowerSortThings);
Лучше в 2 строки сделать цикл

2021-04-03 21:12 UTC, thehighestmath commented on Pya/lab3/src/main.cpp
> +            answer = doSearchInDepth(initDestVer, 10000);
Откуда взялась константа 10000?

2021-04-03 21:33 UTC, thehighestmath requested changes

2021-04-03 21:33 UTC, thehighestmath commented on Pya/lab3/src/main.cpp
> +    void writeData(int sum) {
Делаем `bool` и называем переменную как-нибудь `isResult`или как-то так, а то я 5 минут пытался понять почему в одном месте делить в функцию 0, а в другом максимальный поток(

2021-04-03 21:37 UTC, thehighestmath commented
__Проверено__

0. Наверно лучше в тестировании алгоритма не делать табличку из 3 колонок, а сделать из 2, ну или столбец "Нумерация" ужать, ведь в нем не много данных, в отличии от последнего столбца [так приятнее будет смотреть на табличку ;) ]
 
1. Это ведь сколько памяти занимает граф, но не это долджно быть тут
![image](https://user-images.githubusercontent.com/42893255/113492007-95fcfb80-94dd-11eb-9fb2-d9911cfa3c03.png)
Алгоритм выполняется на графе, и тут должно быть только то, что выделяет / использует только наш алгоритм (включая поиск в глубину). И лучше указывать, что изначает N, потому что ниже это максимальный поток ;( 

2. (+) Коментариев в коде маловато(

3. (+) Как ищется путь видно, но лучше в конце того как его полность отыскали его ещё раз напечатать (с узким горлышком)

__Зачтено на 3 очка, +ф__

2021-04-03 22:47 UTC, SonKhwa commented on Pya/lab3/src/main.cpp
> +}
Совсем не понимаю, как использовать функцию в качестве предиката с отрицанием в сортировке, простая подстановка восклицательного знака перед предикатом не работает.

2021-04-03 22:47 UTC, SonKhwa commented on Pya/lab3/src/main.cpp
> +using Weight = int;
У меня свои тараканы в голове, которые хотят так делать, я не могу их остановить).

2021-04-04 00:42 UTC, SonKhwa commented
Исправлено

2021-04-04 06:57 UTC, thehighestmath approved these changes
Ну уже лучше выглядит :)

2021-04-04 06:57 UTC, thehighestmath commented on Pya/lab3/src/main.cpp
> +}
Функция может вызвать другую функцию)

2021-04-04 22:40 UTC, thehighestmath commented
__Проверено__

0. Исправлено
1. Исправлено
2. Не исправлено
3. Исправлено
4. Не исправлено

__Зачтено на 4 очка, +я__

2021-04-04 22:46 UTC, thehighestmath commented
Защита будет в дискорде

2021-04-04 23:15 UTC, closed without merging