lab4 - Rusinov
Mikhail-M12/PiAA_9382_LETI2021 pull request #31
Opened 2021-04-06 22:35 UTC by lastrise

2021-04-07 08:10 UTC, thehighestmath requested changes

2021-04-07 08:10 UTC, thehighestmath commented on rusinov/lab4/main.cpp
> +std::string getArrowString(int stringLength, int index) {
https://docs.microsoft.com/ru-ru/cpp/parallel/amp/reference/index-class?view=msvc-160
Кажется что не оч называть переменные как класс(

2021-04-07 08:10 UTC, thehighestmath commented on rusinov/lab4/main.cpp
> +        if (i == index) string += "\u2193";
Можно было сделать не такую стрелку `\u2193"`, а такую `v`, но ладно ;)

2021-04-07 08:10 UTC, thehighestmath commented on rusinov/lab4/main.cpp
> +void firstTask(std::string & text, std::string & pattern) {
Лучше `const std::string &`)

2021-04-07 08:10 UTC, thehighestmath commented on rusinov/lab4/main.cpp
> +    } else std::cout << -1;
```suggestion
    } else {
        std::cout << -1;
    }
```

2021-04-07 08:10 UTC, thehighestmath commented on rusinov/lab4/main.cpp
> +    else std::cout << -1;
Лучше не писать в одну строчку

2021-04-07 08:47 UTC, lastrise commented on rusinov/lab4/main.cpp
> +std::string getArrowString(int stringLength, int index) {
Это про какую переменную?

2021-04-07 08:48 UTC, lastrise commented on rusinov/lab4/main.cpp
> +        if (i == index) string += "\u2193";
Мне такая больше нравится

2021-04-07 09:01 UTC, thehighestmath commented on rusinov/lab4/main.cpp
> +std::string getArrowString(int stringLength, int index) {
`index` -- кажется это имя класса

2021-04-07 09:01 UTC, thehighestmath commented on rusinov/lab4/main.cpp
> +        if (i == index) string += "\u2193";
Оки)

2021-04-07 09:02 UTC, thehighestmath commented
![image](https://user-images.githubusercontent.com/42893255/113840178-156a2380-9799-11eb-829c-88b6e4de831b.png)
Лаба не про префиккс функции
Нужно привести только 2 задания
КМП и сдвиг

2021-04-07 13:19 UTC, lastrise commented
Исправлено

2021-04-08 09:58 UTC, thehighestmath commented
_Note_:
* Код лучше закинуть в `src`
* В тестировании достаточно только одного полного теста


__Проверено__

1. (+) Не нашел функций и структур данных(

__Зачтено__ 4 очка +кя

2021-04-08 10:00 UTC, thehighestmath commented
Если хочешь, то можно сегодня около 20:00 защититься в дискорде (без плюсика за функции)

2021-04-08 17:22 UTC, closed without merging