Kruglova - lab1
Mikhail-M12/PiAA_9382_LETI2021 pull request #34
Opened 2021-04-08 12:20 UTC by somewaytolive

first commit

2021-04-08 14:59 UTC, thehighestmath requested changes

2021-04-08 14:59 UTC, thehighestmath commented on Kruglova/lb1/src/lab1.cpp
> +bool tryAbilityToAddSquare(std::vector<std::vector<int>>& mainSquare, int x, int y, int sizeOfSmallSqr)
Лучше передать не просто ссылку, а константную ссылку)

2021-04-08 14:59 UTC, thehighestmath commented on Kruglova/lb1/src/lab1.cpp
> +void printMainSquare(std::vector <std::vector <int>>& mainSquare, int compr, int sizeOfMainSquare)
Лучше передать не просто ссылку, а константную ссылку) + метод ничего не меняет, можно сделать его константым)

2021-04-08 14:59 UTC, thehighestmath commented on Kruglova/lb1/src/lab1.cpp
> +void initMainSqrWithZeros(std::vector<std::vector<int>>& mainSquare, int sizeOfMainSquare) // заполнен нулями == не поставлено ни одного квадрата
Лучше передать не просто ссылку, а константную ссылку)

2021-04-08 14:59 UTC, thehighestmath commented on Kruglova/lb1/src/lab1.cpp
> +    }
Круто) Но точно ли мы только 1 раз можно сжать квадрат?

2021-04-08 14:59 UTC, thehighestmath commented on Kruglova/lb1/src/lab1.cpp
> +    if ( (currCountOfSmallSqrs == (bestCountOfSquares - 1)) && (freeAreaOfMainSquare) )
А точно столько скобок нужно?)

2021-04-08 14:59 UTC, thehighestmath commented on Kruglova/lb1/src/lab1.cpp
> +    if ( (currCountOfSmallSqrs == (bestCountOfSquares - 1)) && (freeAreaOfMainSquare) )
![image](https://user-images.githubusercontent.com/42893255/114049331-0916c100-9894-11eb-842a-3ff8f0773a87.png)

2021-04-08 14:59 UTC, thehighestmath commented on Kruglova/lb1/src/lab1.cpp
> +    if ( ((sizeOfSmallSqr + 1) <= (sizeOfMainSquare / 2)) && (currCountOfSmallSqrs == 3) )
![image](https://user-images.githubusercontent.com/42893255/114049343-0c11b180-9894-11eb-8665-55cccfd7430e.png)

2021-04-08 14:59 UTC, thehighestmath commented on Kruglova/lb1/src/lab1.cpp
> +    if ( (currCountOfSmallSqrs + 1) == bestCountOfSquares)
Тоже вопросик про скобки

2021-04-08 15:06 UTC, thehighestmath commented
__Проверено__

0. Это ведь индивидуализация задания, т.е. логичнее расположить её после задания
![image](https://user-images.githubusercontent.com/42893255/114050038-9b1ec980-9894-11eb-9ac9-ee48bba815c0.png)
1. Ну указаны все оптимизации
2. Графика нет(
![image](https://user-images.githubusercontent.com/42893255/114049901-817d8200-9894-11eb-9b59-0d99e85f9c30.png)
3. Что считаем за операцию?
4. (ф) Не описаны все функции и структуры данных
5. (я) Нет отрисовки карт, просто инфа о том, что "вставляется квадрат", а хотелось бы видеть матрицу, кода этот квадрат поместили


__Зачтено__ на 2,5 очка , +к

2021-04-10 10:50 UTC, somewaytolive commented
Некоторые скобки были сохранены для удобства чтения булевского уравнения.

2021-04-10 11:45 UTC, thehighestmath commented
_Скобок у тебя всё равно много, лучше столько не писать_

__Проверено__

0. +
1. -
2. +
3. -
4. - 
5. -

Зачтено на 3 очка, +к

2021-04-12 20:21 UTC, thehighestmath commented
Завтра (13.04) в 12:00 защита устроит?

2021-04-13 14:04 UTC, closed without merging