lab2 - Kuzmin
Mikhail-M12/PiAA_9382_LETI2021 pull request #37
Opened 2021-04-10 04:24 UTC by dmitrikuz

Вариант 4

2021-04-10 07:22 UTC, thehighestmath commented
Недостаточный комплект для сдачи

2021-04-10 19:09 UTC, dmitrikuz commented
Добавлен скрипт для тестов

2021-04-10 19:19 UTC, thehighestmath commented
Классный скрипт для тестов =)
Мэйкфайла нет

2021-04-10 19:30 UTC, dmitrikuz commented
Добавил

2021-04-11 10:50 UTC, thehighestmath requested changes
Ну и местами оочень много пустых строк

2021-04-11 10:50 UTC, thehighestmath commented on Kuzmin/lab2/src/main.cpp
> +void aStar(Graph a, char name1, char name2, char name3) {
`a` ?) Точно подходящее имя для графа?

2021-04-11 11:12 UTC, thehighestmath commented
__Проверено__

1. Нет промежуточных данных
2. (+) Мало комментариев в коде
3. Бог даст и E - будет Edges (колво ребер) Ну и V понятно что Vertex, но лучше поправить этот момент
![image](https://user-images.githubusercontent.com/42893255/114301990-be818880-9acf-11eb-8684-72acb99bface.png)

Зачтено на 3 очка, +фк

2021-04-11 12:59 UTC, dmitrikuz commented
Поменял имя графа. А почему промежуточных данных нет? Надо еще какие-то добавить?
https://user-images.githubusercontent.com/54910797/114304952-7f0e6880-9ade-11eb-8d91-097489c59828.png

2021-04-11 13:00 UTC, thehighestmath commented
Я не подумал, что они включаются define'ом( Моя ошибка

2021-04-11 13:00 UTC, thehighestmath approved these changes

2021-04-11 13:03 UTC, thehighestmath commented
__Проверено__

1. Исправлено
2. Не исправлено
3. Не исправлено

Зачтено на 4 очка, +фя

2021-04-12 20:22 UTC, thehighestmath commented
Завтра (13.04) в 12:30 защита устроит?

2021-04-12 20:32 UTC, dmitrikuz commented
Да, хорошо

2021-04-13 09:51 UTC, closed without merging