Lab3 - Jerusalimov
Mikhail-M12/PiAA_9382_LETI2021 pull request #46
Opened 2021-04-25 16:56 UTC by NereusOcean

add lab3

2021-04-26 06:04 UTC, thehighestmath commented
А makefile есть?)

2021-04-26 06:05 UTC, thehighestmath requested changes

2021-04-26 06:05 UTC, thehighestmath commented on Jerusalimov/lab3/src/main.cpp
> +using namespace std;
;(

2021-04-26 12:55 UTC, NereusOcean commented on Jerusalimov/lab3/src/main.cpp
> +using namespace std;
Стоит убрать namespace std  и везде использовать этот префикс?
Просто эта программа  дальше не будет улучшаться, там не будет использоваться новые namespace которые могли бы вызвать конфликт, переопределение методов и  т.д.
Все равно исправить?

2021-04-27 13:11 UTC, NereusOcean commented
Добавил Make

2021-04-27 15:10 UTC, thehighestmath commented on Jerusalimov/lab3/src/main.cpp
> +using namespace std;
Я хочу, чтобы мы с вами со всеми старались писать не очень плохой код

2021-04-27 21:47 UTC, thehighestmath commented
Не ок(

![image](https://user-images.githubusercontent.com/42893255/116316440-9e81e280-a7ba-11eb-87c2-e644d0dabce6.png)

-------

__Проверено__
0. Кажется надо по-другомую Разве в пред отчетах у тебя было также?
![image](https://user-images.githubusercontent.com/42893255/116316640-eb65b900-a7ba-11eb-9aa2-738fe5274cba.png)

1. :-(
![image](https://user-images.githubusercontent.com/42893255/116316712-033d3d00-a7bb-11eb-936b-8927d28fdcce.png)

2. Лучше моноширный шрифт
![image](https://user-images.githubusercontent.com/42893255/116316779-1c45ee00-a7bb-11eb-88de-8fb49a10da4c.png)

3. Нет сложностей (_или я слепой_)

WTF?(
![image](https://user-images.githubusercontent.com/42893255/116316553-ca04cd00-a7ba-11eb-88f8-f99598736fac.png)

__Зачтено__ на 2,5 очка +фкя

2021-04-27 22:04 UTC, Mikhail-M12 commented
Нет оценки сложностей и неправильный результат - больше 2 очков быть не может. Также проверьте, пожалуйста, что код на Stepik соответствует коду в пул-реквесте и отчёте.

2021-04-27 22:06 UTC, thehighestmath commented
Ответ правильный, просто нулевые веса странно отображаются, поэтому я
выставил такие очки студенту. Надеюсь правильно я решил

ср, 28 апр. 2021 г., 01:04 Mikhail-M12 ***@***.***>:

> Нет оценки сложностей и неправильный результат - больше 2 очков быть не
> может. Также проверьте, пожалуйста, что код на Stepik соответствует коду в
> пул-реквесте и отчёте.
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Mikhail-M12/PiAA_9382_LETI2021/pull/46#issuecomment-827966717>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AKHH7R6KDZTNJROZQERNDKDTK4YITANCNFSM43ROY4EQ>
> .
>

2021-04-27 22:09 UTC, Mikhail-M12 commented
Если нулевые веса странно отображаются В ОТВЕТЕ, то ответ неправильный.

2021-04-27 22:12 UTC, thehighestmath commented
Получается я ошибся
Исправлю сейчас очки

2021-04-29 23:41 UTC, NereusOcean commented
Исправлено

2021-04-30 23:28 UTC, thehighestmath commented
__Проверено__

0. Не исправлено
1. Не исправлено
2. Нет
3. Сложности не появились
4. Исправлено

__Зачтено__ на 2,5 очка, +фкя

2021-05-01 15:20 UTC, NereusOcean commented
Дико извиняюсь. Почему-то не залился отчет.
Теперь должно быть все хорошо

2021-05-04 19:46 UTC, thehighestmath commented
Проверено.
 
Зачтено на 3,5 очка, +фкя.
На защите можно поднять результат до 4 очков

2021-05-05 17:21 UTC, closed without merging