lab4 - Kuzmin
Mikhail-M12/PiAA_9382_LETI2021 pull request #58
Opened 2021-05-07 01:38 UTC by dmitrikuz

2021-05-07 16:15 UTC, thehighestmath requested changes

2021-05-07 16:15 UTC, thehighestmath commented on Kuzmin/lab4/runtests.sh
> +./kmp < tests/test5.txt
Что по циклам?)

2021-05-07 16:15 UTC, thehighestmath commented on Kuzmin/lab4/src/main.cpp
> +		while (1){
С++ же)

2021-05-08 08:29 UTC, dmitrikuz commented
Исправлено

2021-05-12 21:53 UTC, thehighestmath commented
Не полностью приведено задание в отчете
Кажется, лучше задание расположить раньше теоретических положений
И получше отделить задания друг от друга

2021-05-13 12:47 UTC, dmitrikuz commented
Исправлено

2021-05-14 12:11 UTC, thehighestmath commented
__Проверено__

1. Сложность алгоритмов. Что такое n?

Зачтено на 3,5 очка, +фкя

2021-05-26 16:02 UTC, thehighestmath commented
Круто)
Но на защите повысим баллы, если убедишь)

2021-06-02 11:29 UTC, dmitrikuz commented
Когда можно защитить работу?

2021-06-02 14:32 UTC, thehighestmath commented
Защищено на 4 очка, +фкя

2021-06-02 14:32 UTC, closed without merging