Lab1 - Sorokumov
Mikhail-M12/PiAA_9382_LETI2021 pull request #6
Opened 2021-03-11 16:02 UTC by Homry

2021-03-11 16:04 UTC, Homry commented
После сборки проекта файл *.so/*.dll/*.dylib должен находиться в папке DynamicLib.
Можно собирать проект через CMakeList, можно через уже созданный автоматически Makefile.

2021-03-11 17:36 UTC, thehighestmath commented
![image](https://user-images.githubusercontent.com/42893255/110829720-7f320300-82a9-11eb-90e4-7f4cba0f9151.png)

2021-03-11 18:04 UTC, Homry commented
@thehighestmath прошу прощения, изменил.

2021-03-11 18:10 UTC, thehighestmath requested changes
https://www.jetbrains.com/help/phpstorm/reformat-file-dialog.html

![image](https://user-images.githubusercontent.com/42893255/110834055-23b64400-82ae-11eb-87fb-85527e87a36a.png)

2021-03-11 18:10 UTC, thehighestmath commented on Sorokumov/lab1/src/lab1.cpp
> +}
Эта функция модифицирует входные x, y. Это не очевидно и не очень круто. Давай попробуем делать структуру `Point(x, y)`, которую будем возвращать, если пустая клетка есть, а иначе -- `nullptr`

2021-03-11 18:12 UTC, thehighestmath commented
![image](https://user-images.githubusercontent.com/42893255/110834320-75f76500-82ae-11eb-8906-419aaaae05c4.png)
![image](https://user-images.githubusercontent.com/42893255/110834340-7d1e7300-82ae-11eb-878a-f7b80d8d4c7d.png)

2021-03-11 18:38 UTC, thehighestmath commented
__Проверено__

1. Нет описания сложности по памяти
2. Неверный результат при  `n=5` (пруф на скрине) 

Зачтено на 2 очка +фкя

![image](https://user-images.githubusercontent.com/42893255/110837180-fb304900-82b1-11eb-8195-69466a99e0d4.png)

2021-03-17 10:59 UTC, thehighestmath commented
Туки туки) Исправления будут или так защитимся?)

2021-03-18 10:09 UTC, thehighestmath approved these changes

2021-03-18 10:09 UTC, thehighestmath commented on Sorokumov/lab1/src/lab1.cpp
> +}
Ну лучше бы `bool` ну да ладно)

2021-03-18 10:09 UTC, thehighestmath commented on Sorokumov/lab1/src/lab1.cpp
> +    int limit = 2* M_PI * sqrt(sqrt((mul == 1) ? n : mul));//Задаем предельную величину для количества квадратов
Во, уже лучше)

2021-03-18 10:14 UTC, thehighestmath commented
__Проверено__

Зачтено на 4 очка, +фкя

2021-03-18 16:34 UTC, closed without merging