lab4 Sorochina
Mikhail-M12/PiAA_9382_LETI2021 pull request #64
Opened 2021-05-17 14:23 UTC by oorschnai

2021-05-17 19:02 UTC, thehighestmath requested changes

2021-05-17 19:02 UTC, thehighestmath commented on Sorochina/lab4/src/lab4_1.cpp
> +    int k = 0, l = 0; //k - индекс для прохода по тексту, l - по шаблону
Это по нашему, называем переменные непонятно, чтобы дать им смысл в комменатх(

2021-05-17 19:02 UTC, thehighestmath commented on Sorochina/lab4/src/lab4_1.cpp
> +    while (k < t.length())
Плохо, если есть вопросики, спрашивай)

2021-05-17 19:02 UTC, thehighestmath commented on Sorochina/lab4/src/lab4_1.cpp
> +std::vector<int> answer(std::string p, std::string t);
А тут почему не по ссылке а по значению? Копировать плохо ведь, или у есть пруфы, что тут нужно копировать?)

2021-05-17 19:02 UTC, thehighestmath commented on Sorochina/lab4/src/lab4_1.cpp
> +    int k = 0, l = 0; //k - индекс для прохода по тексту, l - по шаблону
АЙ! l вообще плохая переменная, с 1 легко спутать((

2021-05-17 20:25 UTC, thehighestmath commented
__Проверено__

1. Немного не согласен со сложность алгоритма, на защите поднимем очки

Зачтено на 3,5 очка, +ф

2021-05-17 20:26 UTC, thehighestmath approved these changes

2021-05-18 10:31 UTC, oorschnai commented
Добавила комментарии и промежуточные выводы

2021-05-18 11:09 UTC, thehighestmath commented
__Проверено__

Зачтено на 3,5 очка, +фкя

2021-05-18 11:30 UTC, thehighestmath commented
Зачтено на 4 очка, +фкя

2021-05-18 11:31 UTC, closed without merging