lab1 - Pya
Mikhail-M12/PiAA_9382_LETI2021 pull request #7
Opened 2021-03-12 23:38 UTC by SonKhwa

2021-03-13 07:16 UTC, thehighestmath commented
__Critical__ Вижу такое не в первый раз 
![image](https://user-images.githubusercontent.com/42893255/111022617-d12b7380-83e4-11eb-8f5c-e102cbec78fe.png)

Нет makefile'а

2021-03-13 07:25 UTC, thehighestmath requested changes
Явное лучше чем неявно) 
Ну глобальные переменные -- зло

2021-03-13 07:25 UTC, thehighestmath commented on Pya/lab1/main.cpp
> +std::list <square> curArr;
Глобальные переменные зло. Нужно убрать их (возможно мигрировать в класс)

2021-03-13 07:25 UTC, thehighestmath commented on Pya/lab1/main.cpp
> +void showArea(int& N, bool isMin) {
Функция не используется, она точно нужна?

2021-03-13 07:25 UTC, thehighestmath commented on Pya/lab1/main.cpp
> +void showAnswer(int& N, int& k) {
А зачем этой функции передавать N, да ещё и по ссылке?

2021-03-13 07:25 UTC, thehighestmath commented on Pya/lab1/main.cpp
> +}
Эта функция модифицирует входные `x, y`. Это не очевидно и не очень круто. Давай попробуем делать структуру `Point(x, y)`, которую будем возвращать, если пустая клетка есть, а иначе -- `nullptr`

Ну и передача int'ов по ссылке, тоже такое себе, ибо мы можем их модифицировать, а точно ли `N, length` нужно ли открывать для модификации?

От ссылок давай избавимся

2021-03-13 07:25 UTC, thehighestmath commented on Pya/lab1/main.cpp
> +bool findEmptyPlace(int& x, int& y, int& N) {
Если функция не модифицирует `x,y,N` то давай уберём ссылки

2021-03-13 07:25 UTC, thehighestmath commented on Pya/lab1/main.cpp
> +void defineBase(int& N) {
Опять ссылка нужна? Если так, то давай добавим `const` чтобы указать, что эта переменная __не__ будет меняться

2021-03-13 07:25 UTC, thehighestmath commented on Pya/lab1/main.cpp
> +void calculateOptimization(int& N, int x, int y) {
`int &N`

2021-03-14 13:12 UTC, SonKhwa commented
Исправлены недочеты в коде и в отчете

2021-03-14 14:12 UTC, thehighestmath approved these changes

2021-03-14 14:21 UTC, thehighestmath commented
__Проверено__

1. (+) комментариев в коде не нашел(
2. (+) не хватает промежуточных выводов _кажется, что этого малова-то(_
![image](https://user-images.githubusercontent.com/42893255/111071975-a545e600-84e9-11eb-9cc3-e92454f26c9e.png)


Зачтено на 4 балла, +ф

2021-03-14 14:22 UTC, thehighestmath commented
Если будешь добирать плюсики, то попытка не слетает

2021-03-14 14:59 UTC, thehighestmath commented
Защита будет в дискорде https://discord.gg/eqgHncyTWf

2021-03-14 15:27 UTC, Mikhail-M12 commented
>не хватает промежуточных выводов кажется, что этого малова-то(

Последовательность найденных минимальных заполнений и больше ничего - это не просто "маловато", а минус очко. Потому что увидеть, как работает алгоритм, это не позволяет.

Изменено на 3 очка, +ф.

2021-03-14 15:48 UTC, SonKhwa commented
Исправлено

2021-03-14 15:49 UTC, thehighestmath commented
__Проверено__

1. (+) не исправлено
2. исправлено

Зачтено на 4 балла, +фя

2021-03-14 15:54 UTC, thehighestmath commented
Пулл реквест закрою, но если захочешь добрать плюсиков -- исправь отчет и переоткрой пулл реквест, не создавай новый

2021-03-14 15:54 UTC, closed without merging