Kruglova - lab5
Mikhail-M12/PiAA_9382_LETI2021 pull request #70
Opened 2021-05-28 13:46 UTC by somewaytolive

var 4

2021-05-28 13:58 UTC, thehighestmath requested changes
Проверить форматирование

2021-05-28 13:58 UTC, thehighestmath commented on Kruglova/joker/src/joker.cpp
> +using namespace std;
? 
А потом писать `std::`

2021-05-28 13:58 UTC, thehighestmath commented on Kruglova/joker/src/joker.cpp
> +            cout << curr->dbgStr << ':' << endl;
Форматирование

2021-05-28 13:58 UTC, thehighestmath commented on Kruglova/joker/src/joker.cpp
> +        printTrie();
Форматирование

2021-05-28 16:03 UTC, somewaytolive commented
Исправлено :)

2021-05-29 06:59 UTC, Mikhail-M12 commented
Нарушены правила работы с репозиторием.

2021-06-05 14:46 UTC, somewaytolive commented
Иерархия исправлена.

2021-06-07 10:09 UTC, thehighestmath commented
![image](https://user-images.githubusercontent.com/42893255/120999142-75794800-c791-11eb-815e-0e55c9047fa0.png)

Проверить форматирование в отчете

2021-06-08 07:47 UTC, somewaytolive commented
> Проверить форматирование в отчете

Исправлено

2021-06-08 19:46 UTC, thehighestmath commented
Межстрочный интервал(
![image](https://user-images.githubusercontent.com/42893255/121247782-4f47cb00-c8ab-11eb-92ec-770e0de5170a.png)

Глаз же дергается(

2021-06-08 21:46 UTC, thehighestmath commented
Проверено

Зачтено на 4 очка, +фкя

2021-06-10 13:56 UTC, closed without merging