lab4 - Yuryev
Mikhail-M12/PiAA_9382_LETI2021 pull request #75
Opened 2021-06-04 17:45 UTC by sergeyyurev

2021-06-04 19:04 UTC, thehighestmath requested changes
Что-то не так с форматированием(

2021-06-04 21:29 UTC, thehighestmath commented
Скрины заданий не вписываются в общее форматирование отчета

2021-06-05 05:45 UTC, Mikhail-M12 commented
Да, масштаб следует сделать побольше.

2021-06-07 14:39 UTC, sergeyyurev commented
Исправлено

2021-06-07 18:09 UTC, thehighestmath commented
Проверено

1. Нет сложности для алгоритма циклического сдвига

Зачтено на 3 очка, +фкя

2021-06-08 09:02 UTC, sergeyyurev commented
Исправлено

2021-06-08 19:22 UTC, thehighestmath commented
Проверено

Зачтено на 4 очка, +фкя

2021-06-09 11:18 UTC, thehighestmath commented
Зачтено на 4 очка, +фкя

2021-06-09 11:18 UTC, closed without merging